# Copyright (C) 2005 - 2023 Settlers Freaks <sf-team at siedler25.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: Sanity check

on:
  push:
  pull_request:

jobs:
  FilesSorted:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Remove flaky apt repos
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
          for apt_file in `grep -lr bazel-apt /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gettext
      - name: Sort files
        run: |
          absPotFile="$PWD/rttr.pot"
          find -name '*.po' -print0 | xargs -n1 -0 --replace \
            msgmerge --sort-output --no-wrap --quiet --update --backup=none {} ${absPotFile}
      - name: Check diff
        run: |
          if ! git diff --quiet; then
            echo 'Translation files are not properly sorted.'
            echo 'Run `make -B translations` from inside the RTTR build directory, sort via msgmerge or apply the following patch:'
            git diff --exit-code
          fi
